### PR TITLE
Corrections in the README file.

### PR DESCRIPTION
**Pull request by bert**

### CODE REVIEW

**Comment by oalders** [comment]
Thanks for this!  This is actually a read only repository.  Perhaps @sciurius could say where this pull request should be sent?

**Comment by sciurius** [comment]
There is currently no git repo for eps2png. I'm gradually moving all my software to git on github and I'll setup an eps2png repo one of these days.
Stay tuned.

**Comment by bert** [comment]
Hi, we use the eps2png perl script (a version from 2001) since many years in our pcb application (pcb.geda-project.org) to build the User Manual documentation. After a recent release one of our users mentioned an issue with ghostscript (GPL Ghostscript 9.50: Unrecoverable error, exit code 1). Upon investigating what is causing this I stumbled upon this repository. I think there have to be done some changes to this script regarding explicit control of paths (in/out) introduced in ghostscript version 9.50, changes both for old versions as well as the new version. To be continued. BTW: I understand that this PR will probably be merged in the new repo and not in this one.

**Comment by oalders** [comment]
> There is currently no git repo for eps2png

You can always fork this one if you're feeling lazy. :)

**Comment by sciurius** [comment]
I think I have a little bit more history in my CVS repo ;).

**Comment by sciurius** [comment]
Repository for eps2png is up and running.
https://github.com/sciurius/eps2png
I have released version 2.8, it has been updated for modern perl and ghostview. Bert's PR has been incorporated.

**Comment by oalders** [comment]
Great!  Thanks @bert and @sciurius.  I will close this PR.  That all happened very quickly.

**Comment by sciurius** [comment]
The current git release (2.9) should fix the GPL Ghostscript 9.50: Unrecoverable error, exit code 1 problem.

**Pull request closed without merging**
